export default {
  db_config: {
    pg_user: 'PGUSER',
    pg_host: 'PGHOST',
    pg_password: 'PGPASSWORD',
    pg_database: 'PGDATABASE',
    pg_port: 'PGPORT',
  },
  cloudinary_name: 'CLOUDINARY_NAME',
  cloudinary_api_key: 'CLOUDINARY_API_KEY',
  cloudinary_api_secret: 'CLOUDINARY_API_SECRET',
  access_token_secret: 'ACCESS_TOKEN_SECRET',
  refresh_token_secret: 'REFRESH_TOKEN_SECRET',
  access_token_expire: 'ACCESS_TOKEN_EXPIRE',
  refresh_token_expire: 'REFRESH_TOKEN_EXPIRE',
  jwt_sign_algorithm: 'JWT_SIGN_ALGORITHM',
  smtp_user: 'SMTP_USER',
  smtp_pass: 'SMTP_PASS',
  verify_email_token_secret: 'VERIFY_EMAIL_TOKEN_SECRET',
  secure_password_generator_length: 'SECURE_PASSWORD_GENERATOR_LENGTH',
  google_client_id: 'GOOGLE_CLIENT_ID',
  google_client_secret: 'GOOGLE_CLIENT_SECRET',
  google_oauth_redirect_url: 'GOOGLE_OAUTH_REDIRECT_URL',
  google_recaptcha_secret_key: 'GOOGLE_RECAPTCHA_SECRET_KEY',
  client_side_base_url: 'CLIENT_SIDE_BASE_URL',
  max_videos_per_user: 'MAX_VIDEOS_PER_USER',
};
