export default {
  port: 5000,
  logLevel: 'info',
  db_config: {
    pg_user: '',
    pg_host: '',
    pg_password: '',
    pg_database: '',
    pg_port: '',
  },
  cloudinary_name: '',
  cloudinary_api_key: '',
  cloudinary_api_secret: '',
  access_token_secret: '',
  refresh_token_secret: '',
  access_token_expire: '',
  refresh_token_expire: '',
  jwt_sign_algorithm: '',
  smtp_user: '',
  smtp_pass: '',
  verify_email_token_secret: '',
  google_client_id: '',
  google_client_secret: '',
  google_oauth_redirect_uri: '',
  secure_password_generator_length: '',
  google_recaptcha_secret_key: '',
};
