import { IVideoSmall } from '../app/features/videoSlice';

export const videos: IVideoSmall[] = [
  {
    video_id: '32523412',
    user_id: 'dsgsdg',
    title: 'This is a test titleThis is a test title',
    thumbnail_url: '/images/video-thumbnail_url-1.jpg',
    username: 'Jordbær',
    profile_picture: '/images/profile_picture.jpg',
    views: 1023,
    created_at: '3 hours ago',
  },
  {
    video_id: '32523412',
    user_id: 'dsgsdg',
    title: 'This is a test title',
    thumbnail_url: '/images/video-thumbnail_url-2.jpg',
    username: 'Jordbær',
    profile_picture: '/images/profile_picture.jpg',
    views: 1056,
    created_at: '3 hours ago',
  },
  {
    video_id: '32523412',
    user_id: 'dsgsdg',
    title: 'This is a test title',
    thumbnail_url: '/images/video-thumbnail_url-3.jpg',
    username: 'Jordbær',
    profile_picture: '/images/profile_picture.jpg',
    views: 1056,
    created_at: '3 hours ago',
  },
  {
    video_id: '32523412',
    user_id: 'dsgsdg',
    title: 'This is a test title',
    thumbnail_url: '/images/video-thumbnail_url-4.jpg',
    username: 'Jordbær',
    profile_picture: '/images/profile_picture.jpg',
    views: 1056,
    created_at: '3 hours ago',
  },
  {
    video_id: '32523412',
    user_id: 'dsgsdg',
    title: 'This is a test title',
    thumbnail_url: '/images/video-thumbnail_url-1.jpg',
    username: 'Jordbær',
    profile_picture: '/images/profile_picture.jpg',
    views: 1056,
    created_at: '3 hours ago',
  },
  {
    video_id: '32523412',
    user_id: 'dsgsdg',
    title: 'This is a test title',
    thumbnail_url: '/images/video-thumbnail_url-4.jpg',
    username: 'Jordbær',
    profile_picture: '/images/profile_picture.jpg',
    views: 1056,
    created_at: '3 hours ago',
  },
  {
    video_id: '32523412',
    user_id: 'dsgsdg',
    title: 'This is a test title',
    thumbnail_url: '/images/video-thumbnail_url-3.jpg',
    username: 'Jordbær',
    profile_picture: '/images/profile_picture.jpg',
    views: 1056,
    created_at: '3 hours ago',
  },
  {
    video_id: '32523412',
    user_id: 'dsgsdg',
    title: 'This is a test title',
    thumbnail_url: '/images/video-thumbnail_url-1.jpg',
    username: 'Jordbær',
    profile_picture: '/images/profile_picture.jpg',
    views: 1056,
    created_at: '3 hours ago',
  },
  {
    video_id: '32523412',
    user_id: 'dsgsdg',
    title: 'This is a test titleThis is a test title',
    thumbnail_url: '/images/video-thumbnail_url-1.jpg',
    username: 'Jordbær',
    profile_picture: '/images/profile_picture.jpg',
    views: 1023,
    created_at: '3 hours ago',
  },
  {
    video_id: '32523412',
    user_id: 'dsgsdg',
    title: 'This is a test title',
    thumbnail_url: '/images/video-thumbnail_url-2.jpg',
    username: 'Jordbær',
    profile_picture: '/images/profile_picture.jpg',
    views: 1056,
    created_at: '3 hours ago',
  },
  {
    video_id: '32523412',
    user_id: 'dsgsdg',
    title: 'This is a test title',
    thumbnail_url: '/images/video-thumbnail_url-3.jpg',
    username: 'Jordbær',
    profile_picture: '/images/profile_picture.jpg',
    views: 1056,
    created_at: '3 hours ago',
  },
  {
    video_id: '32523412',
    user_id: 'dsgsdg',
    title: 'This is a test titleThis is a test title',
    thumbnail_url: '/images/video-thumbnail_url-1.jpg',
    username: 'Jordbær',
    profile_picture: '/images/profile_picture.jpg',
    views: 1023,
    created_at: '3 hours ago',
  },
  {
    video_id: '32523412',
    user_id: 'dsgsdg',
    title: 'This is a test title',
    thumbnail_url: '/images/video-thumbnail_url-2.jpg',
    username: 'Jordbær',
    profile_picture: '/images/profile_picture.jpg',
    views: 1056,
    created_at: '3 hours ago',
  },
  {
    video_id: '32523412',
    user_id: 'dsgsdg',
    title: 'This is a test title',
    thumbnail_url: '/images/video-thumbnail_url-3.jpg',
    username: 'Jordbær',
    profile_picture: '/images/profile_picture.jpg',
    views: 1056,
    created_at: '3 hours ago',
  },
];

export type VideoType = typeof videos[0];
